SELECT
--FROM RAW ORDERS 
    O.*
--FROM RAW CUSTOMER
    ,C.*
--FROM RAW PRODUCT
    ,P.*
    ,(O.ORDER_SELLING_PRICE - O.ORDER_COST_PRICE) AS ORDER_PROFIT
FROM
    {{ ref('RAW_ORDERS') }} AS O
LEFT JOIN
    {{ ref('RAW_CUSTOMER') }} AS C
ON 
    C.CUSTOMERID =O.CUSTOMER_ID
LEFT JOIN 
    {{ ref('RAW_PRODUCT') }} AS P
ON 
    P.PRODUCTID = O.CUSTOMER_ID